- name: Install Python
  hosts: container
  gather_facts: no
  tasks:
    - raw: apk add python3

- name: Install nginx
  hosts: container
  tasks:
    - package:
        name: nginx
        state: present
    - service:
        name: nginx
        enabled: yes
